receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'ad-service'
          scrape_interval: 10s
          static_configs:
            - targets: ['host.docker.internal:8180']
          metrics_path: '/metrics'
        - job_name: 'analytics-service'
          scrape_interval: 10s
          static_configs:
            - targets: ['host.docker.internal:3000']
          metrics_path: '/metrics'
        - job_name: 'bidding-service'
          scrape_interval: 10s
          static_configs:
            - targets: ['host.docker.internal:3001']
          metrics_path: '/metrics'

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  attributes:
    actions:
      - key: db.statement
        action: delete
      - key: db.system
        action: delete

exporters:
  otlp/tempo:
    endpoint: tempo:4327
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9464"
    const_labels:
      label1: value1
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
  debug:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [otlp/tempo, debug]
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [debug] 
