server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag
            time: time
            level: attrs.level
            msg: log
      - json:
          expressions:
            level: level
            timestamp: timestamp
            caller: caller
            message: message
            user_id: user_id
            ad_type: ad_type
            ad_id: ad_id
            bid_amount: bid_amount
            duration_seconds: duration_seconds
            trace_id: trace_id
            span_id: span_id
          source: msg
      - labels:
          stream:
          tag:
          level:
          trace_id:
          span_id:
      - timestamp:
          source: timestamp
          format: RFC3339
      - template:
          source: '{{.message}} Trace: {{.trace_id}} Span: {{.span_id}}'
          template: '{{.message}} Trace: {{.trace_id}} Span: {{.span_id}}'
      - output:
          source: template 