apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: PBFA97CFB590B2093
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: P214B5B846CF3925F
          name: trace_id
        - url: http://localhost:3200/trace/$${__value.raw}
          name: trace_id
          urlDisplayLabel: View in Tempo UI
    
  - name: Tempo
    type: tempo
    uid: P214B5B846CF3925F
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      serviceMap:
        datasourceUid: PBFA97CFB590B2093
      
  - name: Loki
    type: loki
    uid: P8E80F9AEF21F6940
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
      derivedFields:
        # Simple trace linking to Tempo UI
        - datasourceUid: P214B5B846CF3925F
          datasourceName: Tempo
          matcherRegex: "Trace: ([a-zA-Z0-9]+)"
          name: Trace
          url: "$${__value.raw}"

  - name: Alertmanager
    type: alertmanager
    uid: alertmanager
    access: proxy
    url: http://alertmanager:9093
    jsonData:
      implementation: prometheus 